import '../models/challenge.dart';

/// La bibliothèque de défis embarquée : 60 défis écrits à la main, dix par
/// domaine. Quatre défis à objectif par domaine, formant une progression du
/// niveau 1 au niveau 3, et six défis d'opportunité.
abstract final class ChallengeLibrary {
  static const List<Challenge> all = [
    // Bouger
    Challenge(
      id: 'run-2k',
      title: 'Courir 2 km',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.move,
      level: 1,
      estimatedDuration: Duration(minutes: 15),
      context: ChallengeContext.outside,
      validation: ValidationMode.health,
      goalReminder: '→ ton objectif sport',
    ),
    Challenge(
      id: 'walk-45',
      title: 'Marcher 45 minutes',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.move,
      level: 1,
      estimatedDuration: Duration(minutes: 45),
      context: ChallengeContext.outside,
      validation: ValidationMode.health,
      goalReminder: '→ ton objectif sport',
    ),
    Challenge(
      id: 'run-5k',
      title: 'Courir 5 km',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.move,
      level: 2,
      estimatedDuration: Duration(minutes: 35),
      context: ChallengeContext.outside,
      validation: ValidationMode.health,
      goalReminder: '→ ton objectif sport',
    ),
    Challenge(
      id: 'run-8k',
      title: 'Courir 8 km',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.move,
      level: 3,
      estimatedDuration: Duration(minutes: 55),
      context: ChallengeContext.outside,
      validation: ValidationMode.health,
      goalReminder: '→ ton objectif sport',
    ),
    Challenge(
      id: 'ten-push-ups',
      title: 'Dix pompes, là',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.move,
      level: 1,
      estimatedDuration: Duration(minutes: 1),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'all-the-stairs',
      title: 'Les escaliers. Tous.',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.move,
      level: 1,
      estimatedDuration: Duration(minutes: 5),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'stretch-10',
      title: 'Dix minutes d\'étirements',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.move,
      level: 1,
      estimatedDuration: Duration(minutes: 10),
      context: ChallengeContext.home,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'plank-3x1',
      title: 'Gainage : trois fois une minute',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.move,
      level: 2,
      estimatedDuration: Duration(minutes: 5),
      context: ChallengeContext.home,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'bike-errand',
      title: 'Faire une course à vélo',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.move,
      level: 2,
      estimatedDuration: Duration(minutes: 30),
      context: ChallengeContext.outside,
      validation: ValidationMode.health,
    ),
    Challenge(
      id: 'swim-1k',
      title: 'Nager 1 km',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.move,
      level: 3,
      estimatedDuration: Duration(minutes: 45),
      context: ChallengeContext.outside,
      validation: ValidationMode.health,
    ),
    // Lire
    Challenge(
      id: 'read-10-pages',
      title: 'Lire 10 pages',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.read,
      level: 1,
      estimatedDuration: Duration(minutes: 15),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.lockedTimer,
      goalReminder: '→ ton objectif lecture',
    ),
    Challenge(
      id: 'read-20-pages',
      title: 'Lire 20 pages',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.read,
      level: 2,
      estimatedDuration: Duration(minutes: 25),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.lockedTimer,
      goalReminder: '→ ton objectif lecture',
    ),
    Challenge(
      id: 'read-one-chapter',
      title: 'Finir un chapitre',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.read,
      level: 2,
      estimatedDuration: Duration(minutes: 30),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.lockedTimer,
      goalReminder: '→ ton objectif lecture',
    ),
    Challenge(
      id: 'read-45-min',
      title: 'Lire 45 minutes d\'affilée',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.read,
      level: 3,
      estimatedDuration: Duration(minutes: 45),
      context: ChallengeContext.home,
      validation: ValidationMode.lockedTimer,
      goalReminder: '→ ton objectif lecture',
    ),
    Challenge(
      id: 'read-one-poem',
      title: 'Lire un poème. Un seul.',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.read,
      level: 1,
      estimatedDuration: Duration(minutes: 2),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'read-in-bath',
      title: 'Lire dans le bain',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.read,
      level: 1,
      estimatedDuration: Duration(minutes: 20),
      context: ChallengeContext.home,
      validation: ValidationMode.lockedTimer,
    ),
    Challenge(
      id: 'go-to-library',
      title: 'Passer à la bibliothèque',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.read,
      level: 1,
      estimatedDuration: Duration(minutes: 40),
      context: ChallengeContext.outside,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'read-on-bench',
      title: 'Lire sur un banc',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.read,
      level: 2,
      estimatedDuration: Duration(minutes: 30),
      context: ChallengeContext.outside,
      validation: ValidationMode.lockedTimer,
    ),
    Challenge(
      id: 'read-long-article',
      title: 'Un long article, jusqu\'au bout',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.read,
      level: 2,
      estimatedDuration: Duration(minutes: 20),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.lockedTimer,
    ),
    Challenge(
      id: 'reopen-dropped-book',
      title: 'Rouvrir le livre abandonné',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.read,
      level: 3,
      estimatedDuration: Duration(minutes: 45),
      context: ChallengeContext.home,
      validation: ValidationMode.lockedTimer,
    ),
    // Cuisiner
    Challenge(
      id: 'seasonal-veg',
      title: 'Un plat de légumes de saison',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.cook,
      level: 1,
      estimatedDuration: Duration(minutes: 30),
      context: ChallengeContext.home,
      validation: ValidationMode.declarative,
      goalReminder: '→ ton objectif cuisine',
    ),
    Challenge(
      id: 'recipe-from-memory',
      title: 'Refaire une recette, de mémoire',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.cook,
      level: 2,
      estimatedDuration: Duration(minutes: 40),
      context: ChallengeContext.home,
      validation: ValidationMode.declarative,
      goalReminder: '→ ton objectif cuisine',
    ),
    Challenge(
      id: 'pizza-dough',
      title: 'Pâte à pizza maison',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.cook,
      level: 2,
      estimatedDuration: Duration(minutes: 90),
      context: ChallengeContext.home,
      validation: ValidationMode.declarative,
      goalReminder: '→ ton objectif cuisine',
    ),
    Challenge(
      id: 'homemade-bread',
      title: 'Du pain, du début à la fin',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.cook,
      level: 3,
      estimatedDuration: Duration(hours: 3),
      context: ChallengeContext.home,
      validation: ValidationMode.declarative,
      goalReminder: '→ ton objectif cuisine',
    ),
    Challenge(
      id: 'real-vinaigrette',
      title: 'Une vinaigrette digne de ce nom',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.cook,
      level: 1,
      estimatedDuration: Duration(minutes: 5),
      context: ChallengeContext.home,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'write-family-recipe',
      title: 'Noter la recette d\'un proche',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.cook,
      level: 1,
      estimatedDuration: Duration(minutes: 10),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'unknown-vegetable',
      title: 'Acheter un légume inconnu',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.cook,
      level: 1,
      estimatedDuration: Duration(minutes: 20),
      context: ChallengeContext.outside,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'market-no-list',
      title: 'Le marché, sans liste',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.cook,
      level: 1,
      estimatedDuration: Duration(minutes: 40),
      context: ChallengeContext.outside,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'curry-recipe',
      title: 'Tester une recette au curry',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.cook,
      level: 2,
      estimatedDuration: Duration(minutes: 45),
      context: ChallengeContext.home,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'cake-for-nothing',
      title: 'Un gâteau, pour rien',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.cook,
      level: 2,
      estimatedDuration: Duration(hours: 1),
      context: ChallengeContext.home,
      validation: ValidationMode.declarative,
    ),
    // Créer
    Challenge(
      id: 'draw-15',
      title: 'Dessiner 15 minutes',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.create,
      level: 1,
      estimatedDuration: Duration(minutes: 15),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.lockedTimer,
      goalReminder: '→ ton objectif création',
    ),
    Challenge(
      id: 'guitar-chords-20',
      title: '20 minutes d\'accords',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.create,
      level: 1,
      estimatedDuration: Duration(minutes: 20),
      context: ChallengeContext.home,
      validation: ValidationMode.lockedTimer,
      goalReminder: '→ ton objectif création',
    ),
    Challenge(
      id: 'write-one-page',
      title: 'Une page, écrite à la main',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.create,
      level: 2,
      estimatedDuration: Duration(minutes: 20),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.lockedTimer,
      goalReminder: '→ ton objectif création',
    ),
    Challenge(
      id: 'play-full-piece',
      title: 'Un morceau entier, sans s\'arrêter',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.create,
      level: 3,
      estimatedDuration: Duration(minutes: 30),
      context: ChallengeContext.home,
      validation: ValidationMode.declarative,
      goalReminder: '→ ton objectif création',
    ),
    Challenge(
      id: 'sing-out-loud',
      title: 'Une chanson entière, fort',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.create,
      level: 1,
      estimatedDuration: Duration(minutes: 3),
      context: ChallengeContext.home,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'draw-what-you-see',
      title: 'Dessiner ce qui est devant toi',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.create,
      level: 1,
      estimatedDuration: Duration(minutes: 10),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.lockedTimer,
    ),
    Challenge(
      id: 'real-letter',
      title: 'Écrire une vraie lettre',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.create,
      level: 1,
      estimatedDuration: Duration(minutes: 20),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'sketch-facade',
      title: 'Croquer une façade, dans la rue',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.create,
      level: 2,
      estimatedDuration: Duration(minutes: 20),
      context: ChallengeContext.outside,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'fix-broken-thing',
      title: 'Réparer le truc cassé qui traîne',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.create,
      level: 2,
      estimatedDuration: Duration(minutes: 30),
      context: ChallengeContext.home,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'compose-four-bars',
      title: 'Composer quatre mesures',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.create,
      level: 3,
      estimatedDuration: Duration(minutes: 30),
      context: ChallengeContext.home,
      validation: ValidationMode.lockedTimer,
    ),
    // Apprendre
    Challenge(
      id: 'vocab-20',
      title: '20 minutes de vocabulaire, sur papier',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.learn,
      level: 1,
      estimatedDuration: Duration(minutes: 20),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.lockedTimer,
      goalReminder: '→ ton objectif apprentissage',
    ),
    Challenge(
      id: 'revise-30',
      title: 'Réviser 30 minutes',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.learn,
      level: 2,
      estimatedDuration: Duration(minutes: 30),
      context: ChallengeContext.home,
      validation: ValidationMode.lockedTimer,
      goalReminder: '→ ton objectif apprentissage',
    ),
    Challenge(
      id: 'translate-page',
      title: 'Traduire une page, sans aide',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.learn,
      level: 2,
      estimatedDuration: Duration(minutes: 30),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.lockedTimer,
      goalReminder: '→ ton objectif apprentissage',
    ),
    Challenge(
      id: 'deep-work-60',
      title: 'Une heure de travail, sans rien d\'autre',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.learn,
      level: 3,
      estimatedDuration: Duration(hours: 1),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.lockedTimer,
      goalReminder: '→ ton objectif apprentissage',
    ),
    Challenge(
      id: 'sailor-knot',
      title: 'Apprendre un nœud de marin',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.learn,
      level: 1,
      estimatedDuration: Duration(minutes: 10),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'three-trees',
      title: 'Trois arbres du quartier, par leur nom',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.learn,
      level: 1,
      estimatedDuration: Duration(minutes: 20),
      context: ChallengeContext.outside,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'card-trick',
      title: 'Apprendre un tour de cartes',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.learn,
      level: 2,
      estimatedDuration: Duration(minutes: 20),
      context: ChallengeContext.home,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'see-an-exhibition',
      title: 'Voir une expo',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.learn,
      level: 2,
      estimatedDuration: Duration(hours: 1),
      context: ChallengeContext.outside,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'free-talk',
      title: 'Assister à une conférence gratuite',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.learn,
      level: 2,
      estimatedDuration: Duration(minutes: 90),
      context: ChallengeContext.outside,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'poem-by-heart',
      title: 'Un poème, par cœur',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.learn,
      level: 3,
      estimatedDuration: Duration(minutes: 30),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.declarative,
    ),
    // Voir des gens
    Challenge(
      id: 'see-a-friend',
      title: 'Voir un ami, en vrai',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.meet,
      level: 1,
      estimatedDuration: Duration(hours: 1),
      context: ChallengeContext.outside,
      validation: ValidationMode.qrCode,
      goalReminder: '→ ton objectif entourage',
    ),
    Challenge(
      id: 'group-activity',
      title: 'Une activité à plusieurs',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.meet,
      level: 2,
      estimatedDuration: Duration(minutes: 90),
      context: ChallengeContext.outside,
      validation: ValidationMode.qrCode,
      goalReminder: '→ ton objectif entourage',
    ),
    Challenge(
      id: 'host-dinner',
      title: 'Recevoir à dîner',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.meet,
      level: 2,
      estimatedDuration: Duration(hours: 3),
      context: ChallengeContext.home,
      validation: ValidationMode.qrCode,
      goalReminder: '→ ton objectif entourage',
    ),
    Challenge(
      id: 'lost-touch',
      title: 'Revoir quelqu\'un perdu de vue',
      kind: ChallengeKind.goal,
      domain: ChallengeDomain.meet,
      level: 3,
      estimatedDuration: Duration(minutes: 90),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.qrCode,
      goalReminder: '→ ton objectif entourage',
    ),
    Challenge(
      id: 'call-grandma',
      title: 'Appeler ta grand-mère',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.meet,
      level: 1,
      estimatedDuration: Duration(minutes: 10),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'neighbour-first-name',
      title: 'Saluer un voisin, par son prénom',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.meet,
      level: 1,
      estimatedDuration: Duration(minutes: 2),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'write-old-friend',
      title: 'Écrire à un vieil ami',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.meet,
      level: 1,
      estimatedDuration: Duration(minutes: 5),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'coffee-colleague',
      title: 'Proposer un café à un collègue',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.meet,
      level: 1,
      estimatedDuration: Duration(minutes: 20),
      context: ChallengeContext.anywhere,
      validation: ValidationMode.declarative,
    ),
    Challenge(
      id: 'board-game',
      title: 'Une partie de jeu de société',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.meet,
      level: 2,
      estimatedDuration: Duration(hours: 1),
      context: ChallengeContext.home,
      validation: ValidationMode.qrCode,
    ),
    Challenge(
      id: 'run-with-someone',
      title: 'Courir avec quelqu\'un',
      kind: ChallengeKind.opportunity,
      domain: ChallengeDomain.meet,
      level: 2,
      estimatedDuration: Duration(minutes: 45),
      context: ChallengeContext.outside,
      validation: ValidationMode.qrCode,
    ),
  ];
}
